project:
  type: website
  output-dir: docs

website:
  title: "R4DS Study Plan"
  navbar:
    title: "R4DS Syllabus"
    left:
      - href: index.qmd
        text: Home
      - href: syllabus.qmd
        text: Syllabus

format:
  html:
    include-in-header:
      - text: |
          <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
          <script src="https://unpkg.com/@supabase/supabase-js@2"></script>
          <script src="lead.js"></script>